Feature/fiscal comment
akretion/l10n-brazil pull request #103
Opened 2020-03-11 19:45 UTC by DiegoParadeda

Implementados comentários para fiscal.document e fiscal.document.line. 

Os comentários são criados em Fiscal > Configuração > Comentário (é possível testar o comentário na mesma página).

No campo comentário é possível acessar o fiscal document da seguinte maneira:
- "${doc}"
Suas propriedades são acessadas de forma parecida:
- "${doc.amount_total}"

Ao confirmar um documento, os comentários do documento e de suas linhas serão processados e anexados com possíveis comentários manuais adicionados. 

Para adicionar comentários manuais e/ou visualizar os comentários processados:
- Fiscal > Document > Aba Extra Info > Campo Processed comment

No documento e nas linhas (ambos na aba extra info) é possível selecionar quais são os comentários que serão utilizados. Campo comments (many2many tags)

2020-03-11 21:36 UTC, mileo requested changes

2020-03-11 21:36 UTC, mileo commented on l10n_br_fiscal/models/document.py
> +    processed_comments = fields.Text(string="Processed Comments")
Renomear para: Additional data, campo e label

2020-03-11 21:36 UTC, mileo commented on l10n_br_fiscal/models/comment.py
> +    def action_compute_message(self):
Renomeia para action_test_message

2020-03-11 21:36 UTC, mileo commented on l10n_br_fiscal/models/comment.py
> +        lang = env['res.lang']._lang_get(env.context.get('lang') or 'en_US')
Coloque pt_BR por padrão, sem pegar a linguagem do context.

2020-03-11 21:36 UTC, mileo commented on l10n_br_fiscal/models/comment.py
> +    processed_comment = fields.Text(string="Processed Comment")
Renomeia o campo para test_comment e a string tb

2020-03-11 21:36 UTC, mileo commented on l10n_br_fiscal/models/document.py
> +    processed_line_comments = fields.Text(string="Processed Line Comments")
Remover este campo pois não esta sendo usado

2020-03-11 21:36 UTC, mileo commented on l10n_br_fiscal/models/document_line.py
> +    processed_comments = fields.Text(string="Processed Comments")
Renomear para Additional data como no campo de cima

2020-03-13 00:28 UTC, mileo approved these changes

2020-03-13 00:28 UTC, mileo commented on l10n_br_fiscal/data/l10n_br_fiscal_comment_data.xml
> +        <field name="comment">Val Aprox Tributos Federal ${format_amount(doc.amount_tax)}</field>
Isto não esta correto, mas eu conserto na atividade dos tributos aproximados

2020-03-18 13:00 UTC, mileo requested changes

2020-03-18 13:00 UTC, mileo commented on l10n_br_fiscal/models/operation_line.py
> +    additional_data = fields.Text(string="Additional Data")
Esse campo deve ser removido

2020-03-21 00:34 UTC, renatonlima approved these changes

2020-03-21 00:36 UTC, merged