[12.0][FIX] l10n_br_sale: corrige aba taxes  e a divisão das linhas do documento fiscal por gênero
akretion/l10n-brazil pull request #117
Opened 2020-07-30 04:37 UTC by marcelsavegnago

[FIX] l10n_br_sale: corrige o problema problema da aba de taxas de acordo com o gênero fiscal do produto e corrige também a divisão das linhas dos documentos fiscais por tipo de documento.

--
Eu confirmo que eu assinei a CLA e li as recomendações de como contribuir:
- https://odoo-community.org/page/cla
- https://odoo-community.org/page/Contribute

2020-08-12 18:40 UTC, renatonlima requested changes

2020-08-12 18:40 UTC, renatonlima commented on l10n_br_sale/views/sale_view.xml
> +                    <field name="fiscal_genre_id" invisible="1"/>
Não é necessário adicionar esse campo porque ele esta sendo injetado pela visão do mixin https://github.com/akretion/l10n-brazil/blob/12.0-mig-account-fiscal-fixes/l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml#L19

2020-08-12 18:40 UTC, renatonlima commented on l10n_br_sale/models/sale_order.py
> +                            inv_line.document_id = invoice.fiscal_document_id
Eu não sei se isso é necessário, pois no l10n_br_account no método create e write já é tratado isso, https://github.com/akretion/l10n-brazil/blob/12.0-mig-account-fiscal-fixes/l10n_br_account/models/account_invoice_line.py#L140

2020-08-13 19:57 UTC, marcelsavegnago commented on l10n_br_sale/models/sale_order.py
> +                            inv_line.document_id = invoice.fiscal_document_id
Ahh blz. Na PR 909 vem este correção então certo ? Lembro que você ficou de dar uma revisada para poder liberar ela. Posso te ajudar em algo ?

2020-08-13 20:00 UTC, marcelsavegnago commented on l10n_br_sale/views/sale_view.xml
> +                    <field name="fiscal_genre_id" invisible="1"/>
Então, lembro que o sistema se perdia e no caso de serviços apresentava os impostos como se o gênero fosse produto. No módulo de reparos isto era só sair da tela e voltar que os impostos do serviço eram apresentados de forma diferente. No preenchimento Ok, mas ao sair do documento e voltar eu percebi que estava se perdendo.

2020-10-06 22:32 UTC, closed without merging