[FIX] Set document_section
akretion/l10n-brazil pull request #118
Opened 2020-08-31 21:08 UTC by gabrielcardoso21

Alteração necessária para que os documentos criados a partir das vendas sejam classificados corretamente e possam ser visualizados nos menus corretos do módulo fiscal.

2020-08-31 21:27 UTC, mileo commented on l10n_br_sale/models/sale_order.py
> +,# Copyright (C) 2009  Renato Lima - Akretion
TYPO

2020-08-31 21:28 UTC, mileo reviewed
De toda forma isso precisa estar melhor definido, não existem somente esses 2 tipos e documentos.

2020-09-01 15:56 UTC, renatonlima requested changes

2020-09-01 15:56 UTC, renatonlima commented on l10n_br_sale/models/sale_order.py
> +            if document_type.code == '55':
Esse campo deveria ser um campo calculado, só deveria haver o tipo SE, não deveria haver a sessão de nfse_recibos, o RPS deveria ser um status ou evento da NFS-e, já que o RPS vai ser extindo e DPS  que é uma espécie de DANFE da Nota Fiscal de Serviço.

2020-09-01 20:42 UTC, mileo commented on l10n_br_sale/models/sale_order.py
> +            if document_type.code == '55':
Na verdade existem recibos de aluguel e outros recibos. Que não necessariamente são uma nota de serviços nem eletrônica e nem manual... Podemos até deixar eles na mesma sessão. Oq vc acha?

2021-03-09 19:52 UTC, renatonlima commented
Esse PR já foi integrado na OCA

2021-03-09 19:52 UTC, closed without merging