Insert fiscal_operation_line_id on line.section
akretion/l10n-brazil pull request #119
Opened 2020-09-04 19:27 UTC by augustodinizl

Como comentado no pr por mim e pelo Gabriel, este campo ñ estava disponível na view...

2020-09-04 19:32 UTC, mileo approved these changes

2020-09-04 19:46 UTC, marcelsavegnago approved these changes

2020-09-08 13:25 UTC, mileo requested changes
Esta não é a implementação correta, estou analisando uma forma melhor de corrigir o problema.

2020-09-09 16:11 UTC, augustodinizl commented
resolvido pelo @mileo aqui: https://github.com/akretion/l10n-brazil/pull/121

2020-09-09 16:11 UTC, closed without merging