[l10n_br_nfe-ak-filtered][RFC] refactor res.partner class
akretion/l10n-brazil pull request #129
Opened 2021-01-14 04:56 UTC by marcelsavegnago

cc @rvalyi @renatonlima

2021-01-19 18:30 UTC, renatonlima commented on l10n_br_nfe/models/res_partner.py
> +    nfe40_idEstrangeiro = fields.Char(compute='_compute_nfe_data',
Boa!

2021-01-19 18:31 UTC, renatonlima commented on l10n_br_nfe/models/res_partner.py
> +    nfe40_IM = fields.Char(related='inscr_mun')
good catch

2021-01-19 18:31 UTC, renatonlima commented on l10n_br_nfe/models/res_partner.py
> +    _inherit = ['res.partner', 'nfe.40.dest']
@rvalyi Can you check this class attributes?

2021-01-19 18:54 UTC, rvalyi requested changes
Pessoal, esse PR realmente nao me convence. Depois vou olhar com calma, mas eu realmente eu acho que tags como nfe.40.tendereco deveriam sim se mapear para essa class, pois no Odoo res.partner tb eh mero endereco. Depois eh mais uma questao de lidar bem com os overrides dos metodos de mapping para funcionar direitinho qdo vc importa ou exporta uma entidade como partner ou company que tem um endereco dentro ou ligado. Mas na branch 12.0-l10n_br_nfe-ak-filtered eu ja lidei bastante com isso acertando os testes para funcionar. Nao pretendo que lidei com todas situacoes do export em especial mas digo que ja resolvi bastante pepinos (ver os commits que eu fiz) e que me parece razoavel resolver os outros pepinos que tiverem.

2021-01-19 19:30 UTC, marcelsavegnago commented
> Pessoal, esse PR realmente nao me convence. Depois vou olhar com calma, mas eu realmente eu acho que tags como nfe.40.tendereco deveriam sim se mapear para essa class, pois no Odoo res.partner tb eh mero endereco. Depois eh mais uma questao de lidar bem com os overrides dos metodos de mapping para funcionar direitinho qdo vc importa ou exporta uma entidade como partner ou company que tem um endereco dentro ou ligado. Mas na branch 12.0-l10n_br_nfe-ak-filtered eu ja lidei bastante com isso acertando os testes para funcionar. Nao pretendo que lidei com todas situacoes do export em especial mas digo que ja resolvi bastante pepinos (ver os commits que eu fiz) e que me parece razoavel resolver os outros pepinos que tiverem.

Este modelo de dados é algo que estava me dando bastante trabalho nos testes. Bastava instalar algum outro módulo da localização e ele se perdia. Percebi que deixando apenas a tag nfe.40.dest o problema deixava de existir. Em seguida, deixei no padrão das demais classes como por exemplo a NFERelated. Enfim, posso tentar colocar pelo menos a nfe.40.tendereco e ver como fica. Vou testar e coloco aqui a mensagem de erro.. basicamente o sistema passa a informar que campo como CNPJ ou xLgr não existem o campo vai mudando conforme eu mudo a sequencia das heranças.

Obs. os testes que estou fazendo são através da interface, ou seja, são testes utilizando o sistema e através das views.

2021-01-20 02:23 UTC, marcelsavegnago commented
> CNPJ ou xLgr não existem o campo vai mudando conforme eu mudo a sequencia das heranças.

@rvalyi até aqui blz https://github.com/akretion/l10n-brazil/pull/129/commits/984ff86c39ac9b62c33a5165df39f2b23168297b

Mas, se adicionar a herança 'nfe.40.tenderemi' e instalar alguma módulo como por exemplo o l10n_br_sale já começo receber mensagens de erro como a mensagem abaixo

```
/user/oca/l10n-brazil/spec_driven_model/models/spec_export.py", line 27, in _export_fields
    member_spec = ds_class_spec[field_spec_name]
KeyError: 'xLgr'
```

2021-01-20 13:31 UTC, rvalyi commented
valeu pelo report @marcelsavegnago vou tentar olhar isso hoje. Talvez teria que tirar uns related e trocar por _compute/_inverse_compute ou metodos de mapping. Uma outra questao eh que o codigo do field_view_get no spec_model_driven eh so um POC para ajudar a debugar, mas pode ter problemas que vem de la. Esse codigo realmente nao foi finalizado, a ideia seria reusar o codigo do StackModel para percorrer os modelos stacked, talvez com algum yield para monta as visoes. Nao tive tempo. Uma alternativa eh desativar o fields_view_get caso seja ele que estaria criando problemas. Vou fazer o maximo para olhar hoje, pelo menos foi bom vc apontar o problema ja.

2021-01-21 19:46 UTC, marcelsavegnago commented
@renatonlima para a tag do código do país estava buscando o código ibge mas pelo que entendi o correto é o campo bc_code.

Fora isso, adicionei o campo nfe40_xFant 

cc @rvalyi

2021-01-26 15:54 UTC, renatonlima commented
@marcelsavegnago 

Eu como vc fez um commit alterando as propriedades da classe partner relacionados ao spec e o @rvalyi ainda não revisou, eu fiz o cherry-pick dos dois ultimos commits onde você resolve o xFant e o bc_code

https://github.com/akretion/l10n-brazil/commit/bc8a3ee3a03c26453352e61446d09944c6b1dcf1
https://github.com/akretion/l10n-brazil/commit/ec095935f703e6c1418116fc19be7db697483ea0

Você pode fazer o rebase da branch deste PR com a branch da Akretion para atualizar esse PR?

2021-01-26 16:29 UTC, marcelsavegnago commented
> @marcelsavegnago
> 
> Eu como vc fez um commit alterando as propriedades da classe partner relacionados ao spec e o @rvalyi ainda não revisou, eu fiz o cherry-pick dos dois ultimos commits onde você resolve o xFant e o bc_code
> 
> [bc8a3ee](https://github.com/akretion/l10n-brazil/commit/bc8a3ee3a03c26453352e61446d09944c6b1dcf1)
> [ec09593](https://github.com/akretion/l10n-brazil/commit/ec095935f703e6c1418116fc19be7db697483ea0)
> 
> Você pode fazer o rebase da branch deste PR com a branch da Akretion para atualizar esse PR?

@renatonlima Feito

2021-01-26 16:39 UTC, rvalyi commented
blz vou realmente tentar olhar isso hoje a noite. @marcelsavegnago posso te passar uma tarefa nesse modulo para ajudar nos testes?

2021-01-26 16:43 UTC, marcelsavegnago commented
> blz vou realmente tentar olhar isso hoje a noite. @marcelsavegnago posso te passar uma tarefa nesse modulo para ajudar nos testes?

Opa.. Com certeza

2021-01-26 17:19 UTC, rvalyi commented
@marcelsavegnago @renatonlima aqui https://github.com/OCA/l10n-brazil/issues/1106

2021-02-09 15:04 UTC, rvalyi commented
Marcel, vc pode testar de novo com as mudanças que eu fiz ontem e me falar se vc ainda ve algum problema com o esse mapping do partner. Ontem testei de novo com varios modulos e nao vejo problema. Mas eu gostaria se vc tiver um examplo que da zica.

2021-02-09 15:04 UTC, rvalyi commented
cc @marcelsavegnago

2021-02-09 15:25 UTC, marcelsavegnago commented
> Marcel, vc pode testar de novo com as mudanças que eu fiz ontem e me falar se vc ainda ve algum problema com o esse mapping do partner. Ontem testei de novo com varios modulos e nao vejo problema. Mas eu gostaria se vc tiver um examplo que da zica.

Grande @rvalyi ... Já fiz alguns testes ontem e não notei mais nenhum problema. Vou fechar a PR e se surgir algo eu aviso.

Obrigado

2021-02-09 15:25 UTC, closed without merging