[FIX] Amount and Base ST
akretion/l10n-brazil pull request #158
Opened 2021-03-09 19:06 UTC by mileo

2021-03-09 20:11 UTC, renatonlima commented
@mileo,

Antes seria bom a gente aprovar o PR da edição do Documento Fiscal e Fatura https://github.com/OCA/l10n-brazil/pull/1146 e depois dos totais https://github.com/OCA/l10n-brazil/pull/1175 porque depois fica mais fácil para fazer os merges sem ter que resolver conflitos os PRs de hoje https://github.com/OCA/l10n-brazil/pull/1190 https://github.com/OCA/l10n-brazil/pull/1189 já vai dá uns conflitos chatos para resolver no merge dos totais.

2021-03-10 10:11 UTC, rvalyi requested changes
Não é legal que campo de total seja um related, pois ele vai tentar importa-los na importação e isso vai conflitar com o cálculo. Melhor deixar o mappings nos métodos de exportação eu acho.

2021-03-10 10:22 UTC, mileo commented
> Não é legal que campo de total seja um related, pois ele vai tentar importa-los na importação e isso vai conflitar com o cálculo. Melhor deixar o mappings nos métodos de exportação eu acho.

Pode ser, vou conversar com o @gabrielcardoso21 sobre isso hoje cedo e respondo aqui.

2021-03-16 15:24 UTC, renatonlima commented
@rvalyi,

Os campos de totais da NFE (ou pelo menos a maioria deles) são campo que são meramente a somatória dos campos das linhas, por exemplo, o total do ICMS é a soma do valor do ICMS das linhas (inclusive algumas validações da NF-e são realizada para assegurar essa consistência) , então não vejo problema em ser uma related de um campo computed

2021-03-16 15:25 UTC, renatonlima requested changes

2021-03-16 15:25 UTC, renatonlima commented on l10n_br_nfe/models/document.py
Isso ainda não esta implementado, é bom você colocar um TODO aqui...

2021-04-18 16:07 UTC, closed without merging

2021-04-18 16:12 UTC, mileo commented
Replaced by https://github.com/OCA/l10n-brazil/pull/1286