[12.0][FIX] Related technical_support_id as infRespTec
akretion/l10n-brazil pull request #165
Opened 2021-03-25 16:47 UTC by gabrielcardoso21

Add the missing relation for infRespTec.

2021-03-25 19:22 UTC, marcelsavegnago approved these changes

2021-03-29 14:59 UTC, luismalta approved these changes

2021-03-30 04:38 UTC, rvalyi requested changes
hum eu realmente nao sei. Hoje ja temos o responsel tecnico como partner:
https://github.com/akretion/l10n-brazil/blob/12.0-l10n_br_nfe-ak-filtered/l10n_br_nfe/models/res_partner.py#L18
faz sentido, imagina que a KMEE implementa o Odoo numa empresa X, a KMEE é responsavel tecnico e tb fornecedor de TI que vai emitir umas notas.

Sera se erramos com alguma coisa?

cc @renatonlima

2021-03-30 04:43 UTC, rvalyi commented
> hum eu realmente nao sei. Hoje ja temos o responsel tecnico como partner:
> https://github.com/akretion/l10n-brazil/blob/12.0-l10n_br_nfe-ak-filtered/l10n_br_nfe/models/res_partner.py#L18
> faz sentido, imagina que a KMEE implementa o Odoo numa empresa X, a KMEE é responsavel tecnico e tb fornecedor de TI que vai emitir umas notas.
> 
> Sera se erramos com alguma coisa?
> 
> cc @renatonlima

hum falei besteira, precisamos sim ter esse related (hoje temos um patch em prod para isso alias). Agora o force_stack_path isso eu acho que nao precisa nao, pois como temos o responsavel tecnico mapeado num parceiro, ja é um m2o padrao (ainda que related entao) e nao seria um novo objeto que teria que incluir ou nao dentro do modelo do infnfe. Vcs devem ter feito isso no fork de vcs onde nao usavam os mapping correctamente no res,partner, mas eu acho que na branch para a OCA nao vai precisar.

2021-03-31 19:07 UTC, rvalyi commented
@gabrielcardoso21 fiz o cherry-pick desse commit apenas https://github.com/akretion/l10n-brazil/pull/165/commits/4716d03d657541f41549cc8da1d07d04d667641b e as Nfe's ja vem com o responsel tecnico do company certinho. Tb chequei o XML continua exportando certinha o responsavel tecnico. O outro commit nao era preciso nao, portanto fecho esse PR.

2021-03-31 19:07 UTC, closed without merging