[FIX] Compute all tax sign
akretion/l10n-brazil pull request #192
Opened 2022-03-17 22:16 UTC by felipemotter

Correção simples para o problema dos impostos sendo lançados invertidos. (Débito ao invés de Crédito e Crédito no lugar de Débito)

Ainda há alguns erros referentes aos impostos, mas estamos estudando as mudanças feitas no account para poder adaptar as necessidades da localização.

2022-03-17 22:21 UTC, netosjb approved these changes

2022-03-18 18:59 UTC, renatonlima commented
@felipemotter,


Há um tempo atrás eu fiz o PR https://github.com/OCA/l10n-brazil/pull/1797 para corrigir no repartition.line dos account.tax o final do imposto, quando eu faço uma nota o lançamento esta correto:

![image](https://user-images.githubusercontent.com/211005/159067278-754a06a2-af9c-4c24-a839-f3f3435dc167.png)

Então eu acredito que neste o PR não esta correto.

2022-03-18 19:02 UTC, renatonlima commented
Uma coisa que eu estou olhando agora é ao criar uma linha de fatura e salva-la, ao altera-la o valor não é atualizado os totais, e também vou ter que fazer uma correção no caso quando uma operação não tem um conta redutora e os valores dos impostos são deduzidos da receita/despesa

2022-03-18 19:03 UTC, renatonlima requested changes
Há um tempo atrás eu fiz o PR https://github.com/OCA/l10n-brazil/pull/1797 para corrigir no repartition.line dos account.tax o final do imposto, quando eu faço uma nota o lançamento esta correto:

2022-03-18 19:21 UTC, felipemotter commented
@renatonlima nos lançamentos do seu exemplo os sinais estão invertidos, no caso de uma venda os impostos seriam:

D - ICMS s/ Vendas (conta redutora de receita) 
C - ICMS a recolher (aumenta o passivo)

O PR inverte isso no account, o correto seria mexer no coa?

2022-03-18 19:36 UTC, felipemotter commented
@renatonlima o erro de inverter realmente existe, mas estava aqui analisando e a solução correta e você tem razão disso. Deve ser tratado no COA, porque o erro vem de lá. 

Você concorda que o correto seria inverter os sinais que estão hoje? Se sim, eu já irei fechar essa pr e abrir uma correção direto no repositório da localização.

Outra coisa que gostaria de propor, seria por que essas taxas dedutíveis já sejam padrões nas operações, pois acredito que é o caso mais comum no Brasil.

2022-03-19 17:36 UTC, felipemotter commented
Fala @renatonlima passei o sábado estudando suas observações e cheguei a algumas conclusões.

Tentei resolver o problema direto pelo COA mas no fim vi que não era o lugar correto para para correção e me arrisco a dizer que esse PR continua sendo a melhor forma de resolver o problema.

Tentando explicar meu ponto:

O factor_percent que você trabalhou na PR https://github.com/OCA/l10n-brazil/pull/1797 , a fim de alterar o comportamento nos impostos dedutíveis, tem a função de dividir valores entre contas ou inverter o comportamento previsto para cada tipo de operação.

Um exemplo(estou colocando apenas icms para facilitar): 
Considerando uma operação **SEM** impostos dedutiveis é previsto que um imposto normal, com apenas uma linha com factor_percent 100, em uma fatura de venda, seja um crédito como na imagem a seguir:
![comportamento-imposto-venda-padrao](https://user-images.githubusercontent.com/6812128/159130712-6cb2a44b-df31-4721-8cb2-048a44ab1229.png)

Considerando uma operação COM impostos dedutíveis, ele é uma operação inversa ao que seria esperado, ou seja, o factor_percent é de -100. Então em uma venda é previsto que ele seja um débito. Ilustrei na imagem a seguir o lançamento:
![comportamento-imposto-dedutivel-venda-padrao](https://user-images.githubusercontent.com/6812128/159130956-aa4ed81e-692f-4eda-8bf1-a6c335f62738.png)

Um imposto dedutível é o inverso do imposto normal, então a modificação na PR https://github.com/OCA/l10n-brazil/pull/1797 está correta, porém a forma que esses impostos são calculados pela localização faz com que essa inversão não faça efeito.

Na seguinte linha, onde os valores dos impostos são calculados pela localização, o valor do factor_percent é ignorado e o amount é sempre trazido positivo: (confesso que não estudei muito esse método, porque não tive mais tempo)
https://github.com/akretion/l10n-brazil/blob/2636c31efa1ec5a740856552cf66a47d5cb6819f/l10n_br_account/models/account_tax.py#L80

Mas pelo que eu entendi, esse comportamento já foi previsto por você, já que aqui você inverte a força o sinal para que seja o contrário da operação padrão:
https://github.com/akretion/l10n-brazil/blob/2636c31efa1ec5a740856552cf66a47d5cb6819f/l10n_br_account/models/account_tax.py#L134

O odoo preve que o valor do amount tenha que ser negativo para ser conserado um crédito, e por isso, sempre trata os impostos como negativos em caso de fatura de venda. Assim eu fiz esse tratamento previsto nessa PR, onde os valores trazidos pelo compute_taxes são negativados em caso de venda e inalterados para compra. (Os dedutíveis são ao contrário como já acontecia)

Por não ter estudado o metodo compute_taxes e por acreditar que a necessidade dos valores negativos sejam especificamente para esse caso dos lançamentos contábeis, acredito que a alteração denrto do compute_all após o compute_taxes seja a correção mais viável. 

Desculpe o texto gigante e o detalhamento exagerado, mas é que não iria conseguir expressar corretamente o que desejo falar se não descrevesse toda a minha linha de pensamento.

2022-03-24 13:44 UTC, renatonlima commented
Olá @felipemotter,


Eu seu comentário e analisei o código tanto no account quanto do seu PR, no Odoo o compute_all do account.tax recebe o contexto force_sign para utiliza-lo no calculo do imposto e também é utilizado o factor no repartition.line, então na localização deveríamos utilizar o factor do repartition.line também, eu fiz um commit para implementar e corrigir o método compute_all no account.tax https://github.com/akretion/l10n-brazil/commit/78171095c6c3289056001a0dbaccfee17cd17a12

2022-03-24 16:17 UTC, felipemotter commented
Certo @renatonlima, pena que meu PR não foi aproveitado, mas que bom que ajudei você com o raciocínio. 

Uma dúvida, como você já tem mais experiência no account, a ajuda aqui no fork de vocês está sendo útil?

2022-03-25 14:31 UTC, renatonlima commented
@felipemotter,

Toda ajuda é bem vinda sim, ter mais pessoas ajudando a revisar o código e o escopo funcional ajuda ajuda nesse processo de migração, eu só diria que se vocês forem trabalhar neste PR seria bom a gente combinar as tarefas que vocês querem ajudar. 

Ao longo desta semana eu trabalhei na migração do l10n_br_account e consegui resolver a maioria dos problemas na criação e edição da fatura e do documento fiscal, ainda existe um problema na alteração dos valores das linhas de produtos, mas estou perto de conseguir resolver isso. Existe algumas tarefas nesse PR que se vocês quiserem ajudar, listo algumas aqui:

- Migrar a geração de uma devolução (REFUND) de um documento fiscal;
- Incluir testes para lançamento de faturas não fiscais e verificar se elas estão ligadas aos dummys de cada empresa corretamente;
- Incluir teste para ao criar uma aliquota (fiscal.tax) se ele vai ser relacionado automaticamente ao account.tax (inclusive tenho que fazer o port de alguns correções feitas recentemente na 12.0)

2022-03-25 16:37 UTC, felipemotter commented
Certo Renato, pode deixar. Obrigado pelo feedback.

2022-03-25 17:11 UTC, closed without merging