NFe 4.00 - Alterações/Validações Ambiente de Homologação - entram em produção 01/09/2018
akretion/l10n-brazil pull request #77
Opened 2018-07-18 15:00 UTC by mbcosta

Ambiente de homologação está validando campos que só serão feitos em produção em 01/09/2018, porém isso esta inviabilizando testes com NFes, obrigando a serem feitos diretamente no ambiente de produção, por isso nesse PR vou tentar corrigi-los.

2018-07-18 15:00 UTC, mbcosta commented
Ao enviar uma nota está retornando Erro 852 - Rejeição: Número da parcela inválido ou não informado [nOcor:1] o campo nDup agora só aceita valores '001', '002', '003' etc

2018-07-18 17:33 UTC, mbcosta commented
É preciso informar o campo vLiq, sem isso acontece o erro abaixo
Erro 851 - Rejeição: Soma do valor das parcelas difere do Valor Líquido da Fatura

2018-07-20 20:05 UTC, mbcosta commented
O codigo EAN está sendo alterado p/ o GTIN, por isso é preciso implementar o GTIN, por enquanto estou enviando 'SEM GTIN' para evitar o erro da SEFAZ 883 - Rejeição: GTIN (cEAN) sem informação

2018-08-10 12:36 UTC, mileo requested changes

2018-08-10 12:36 UTC, mileo commented on l10n_br_account_product/sped/nfe/document.py
> +                invoice_line.fiscal_uom_ean or 'SEM GTIN'
Isso não esta correto.

Devemos ter um campo de unidade tributária no NCM, pois isto esta definido em na tabela de NCM.

http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=BYRQ4VAVk74=

2018-08-10 12:39 UTC, mileo commented on l10n_br_account_product/sped/nfe/document.py
> +                invoice_line.fiscal_uom_ean or 'SEM GTIN'
Referente ao EAN vale a informação do GS1:
https://www.gs1br.org/faq/diferenca-cean-ceantrib

Quanto a NCM x UN de medida comentado é para campo uTrib.

2018-08-13 19:20 UTC, mbcosta commented on l10n_br_account_product/sped/nfe/document.py
> +                invoice_line.fiscal_uom_ean or 'SEM GTIN'
ola @mileo , você acredita que isso deve ser resolvido ainda na 8.0 ? Colocar a Unidade Tributaria no NCM não acabaria "engessando" o código ? Já que assim todos os produtos dentro daquele NCM estariam com o mesma unidade tributária. No exemplo do link a solução hoje dentro do programa não seria ter cadastrado os 3 produtos : 
- Lata 
- Caixa ( com uma Lista de Produtos contendo as Latas )
- Palete ( com uma Lista de Produtos contendo as caixas ) 

E assim permitindo a configuração esperada. Esse problema parece ir além da unidade tributária, seria preciso verificar como essa situação deve ser feita dentro do programa, envolve outras questões tanto de logística quanto de contabilidade e talvez seja preciso analisar caso a caso

2018-08-14 18:45 UTC, merged