Feature/workflow documentos fiscais
akretion/l10n-brazil pull request #92
Opened 2020-02-07 20:23 UTC by mileo

Base para a emissão de nf-e

2020-02-12 17:33 UTC, rvalyi commented on l10n_br_account/models/fiscal_tax_group.py
> +            return super(FiscalTaxGroup, self).create(values)
good catch!

2020-02-12 17:34 UTC, rvalyi commented on l10n_br_account/models/fiscal_document.py
> +    fiscal_doc_date = fields.Datetime(related="date", readonly=False)
I just had to do the same fix when attempting to rebase, so yes.

2020-02-29 15:04 UTC, renatonlima requested changes
Eu fiz alguns comentários na revisão, mas acho que dar para aceitar o PR e fazer essas correções depois, para não o time da KMEE não precisar perder tempo em fazer o rebase para integrar o que eles precisaram fazer no l10n_br_fiscal para trabalhar com a NF-e, eu diria que só resolver o que comentei no manifest e podemos fazer o merge do PR.

2020-02-29 15:04 UTC, renatonlima commented on l10n_br_account/__init__.py
> +# from . import report
Poderia remover esse comentário já que foi removido a pasta report.

2020-02-29 15:04 UTC, renatonlima commented on l10n_br_account/__init__.py
> +# from . import report
Acho que poderia remover essa linha já foi removida a pasta report

2020-02-29 15:04 UTC, renatonlima commented on l10n_br_fiscal/models/document_abstract.py
> +        related='document_serie_id.document_type_id',
Não precisa ser related, porque se for editar um documento fiscal no form generico ou um documento emitido por terceiros ele pode escolher um documento fiscal antes da serie.

2020-02-29 15:04 UTC, renatonlima commented on l10n_br_fiscal/models/document_eletronic.py
> +    _inherit = ["mail.thread",
Acho que não precisa ter essa herança, pois o l10n_br_fiscal.document já herda o l10n_br_fiscal.document.electronic, ok?

2020-02-29 15:04 UTC, renatonlima commented on l10n_br_fiscal/__manifest__.py
> +    "author": "Akretion, KMEE, Odoo Community Association (OCA)",
Na minha opinião para ser autor ou co-autor do módulo deve seguir um critério semelhante ao que foi discutido no https://github.com/OCA/l10n-brazil/pull/715:

1. Ser autor ou co-autor na criação do módulo;
2. Ter contribuição maior ou semelhante dos autores do módulo.

Eu analisei a quantidade de linhas inseridas nos commits deste módulo e a contribuição de vocês esta em torno de 10% , não justifica estar como autores do módulo e sim como contribuidores como você já esta. Nos reconhecemos que o time da KMEE faz contribuições importantes ao projeto e o @mileo como integrante do PSC do projeto tem papel na liderança do projeto e reconhecemos seus esforços. Como lideres do projeto um dos benefícios é ter esse reconhecimento e visibilidade, por exemplo a KMEE é autora de módulo como HR, POS da localização e também não seria justo que alguém que contribuísse cerca 10% ser autores deste módulos, deve estar como contribuidores e não como autores, esse critério deve ser respeitado.

2020-03-03 19:57 UTC, merged