[NEW] CFOP Entrada e Devolução
akretion/l10n-brazil pull request #94
Opened 2020-03-04 19:36 UTC by mileo

Signed-off-by: Luis Felipe Mileo <mileo@kmee.com.br>

Descrição do problema/nova funcionalidade deste Pull Resquest(PR):
------------------------------------------------------------------

-
-
-

Comportamento atual antes do PR:
--------------------------------

Comportamento esperado depois do PR:
------------------------------------

- [ ] Esta mudança não altera a estrutura do banco de dados, portanto não precisa de script de migração.

--
Eu confirmo que eu assinei a CLA e li as recomendações de como contribuir:
- https://odoo-community.org/page/cla
- https://odoo-community.org/page/Contribute

2020-03-04 20:22 UTC, renatonlima commented
@mileo,

Eu não adicionei os campos "cfop_inverse_id", "cfop_return_id" no arquivo csv de CFOPs porque não dar para usar esses campos neste arquivo, durante a instalação do módulo ao carregar o csv vai ter o problema de referenciar um id que esta em linhas seguintes e não foi carregado e não será contrado.

Por isso que não informo esses campos no csv do CFOP e uso esse arquivo para preencher esses campos. https://github.com/akretion/l10n-brazil/blob/12.0-mig-l10n_br_account_product/l10n_br_fiscal/data/l10n_br_fiscal_cfop_data.xml

Então eu não vejo muito sentido em adicionar esses dois campos

2020-03-04 20:25 UTC, mileo commented
Não tinha visto esse arquivo, desculpe.
Eu refaço isso completando com o que esta faltando.

2020-03-10 12:12 UTC, mileo commented
UP

2020-03-10 12:19 UTC, renatonlima requested changes

2020-03-10 12:19 UTC, renatonlima commented on l10n_br_fiscal/models/tax.py
> +        product = kwargs.get("product")
Acho que você tem que fazer rebase deste commit, para manter essas variáreis comentadas

2020-03-10 12:28 UTC, mileo commented on l10n_br_fiscal/models/tax.py
> +        product = kwargs.get("product")
Feito

2020-03-10 12:35 UTC, renatonlima approved these changes

2020-03-10 12:35 UTC, merged