[ADD] Emissão e recebimento em menus dedicados
akretion/l10n-brazil pull request #98
Opened 2020-03-05 21:38 UTC by mileo

Descrição do problema/nova funcionalidade deste Pull Resquest(PR):
------------------------------------------------------------------

-
-
-

Comportamento atual antes do PR:
--------------------------------

Comportamento esperado depois do PR:
------------------------------------

- [ ] Esta mudança não altera a estrutura do banco de dados, portanto não precisa de script de migração.

--
Eu confirmo que eu assinei a CLA e li as recomendações de como contribuir:
- https://odoo-community.org/page/cla
- https://odoo-community.org/page/Contribute

2020-03-05 21:42 UTC, rvalyi requested changes

2020-03-05 21:42 UTC, rvalyi commented on l10n_br_fiscal/views/l10n_br_fiscal_action.xml
> +            related to a fiscal operation.
aqui fala de operação fiscal, mas o menu eh de documento fiscal
Tb acho que tem um erro de inglês, seria "helps you to easily track" faltou o to.

2020-03-05 21:48 UTC, DiegoParadeda commented on l10n_br_fiscal/views/l10n_br_fiscal_action.xml
> +            related to a fiscal operation.
corrigido, valeu

2020-03-05 21:59 UTC, renatonlima requested changes

2020-03-05 21:59 UTC, renatonlima commented on l10n_br_fiscal/views/l10n_br_fiscal_action.xml
> +        <field name="name">Recebimento</field>
O nome do menu deve estar em inglês

2020-03-05 21:59 UTC, renatonlima commented on l10n_br_fiscal/views/l10n_br_fiscal_action.xml
> +        <field name="name">Emissão</field>
O nome do menu deve estar em inglês

2020-03-05 21:59 UTC, renatonlima commented on l10n_br_fiscal/views/l10n_br_fiscal_menu.xml
> +    <menuitem id="document_in_menu" action="document_in_action" name="Recebimento" groups="l10n_br_fiscal.group_user,l10n_br_fiscal.group_manager" parent="documents_menu" sequence="10"/>
O nome do menu deve estar em inglês

2020-03-05 21:59 UTC, renatonlima commented on l10n_br_fiscal/views/l10n_br_fiscal_menu.xml
> +    <menuitem id="document_out_menu" action="document_out_action" name="Emissão" groups="l10n_br_fiscal.group_user,l10n_br_fiscal.group_manager" parent="documents_menu" sequence="11"/>
O nome do menu deve estar em inglês

2020-03-05 21:59 UTC, renatonlima commented on l10n_br_fiscal/models/document.py
> +    operation_type = fields.Selection(related=False)
Eu não estou certo se deve ser removido o related desse campo, dar para filtrar o domain do campo operation_id com o contexto da action e se você abrir o form com o domain operation_id filtrado ao selecionar a operação fiscal vai ser preenchido o operation_type correto.

2020-03-05 22:05 UTC, mileo commented on l10n_br_fiscal/models/document.py
> +    operation_type = fields.Selection(related=False)
Pode dar um exemplo dessa implementação?

2020-03-05 22:07 UTC, mileo commented on l10n_br_fiscal/models/document.py
> +    operation_type = fields.Selection(related=False)
Creio que a implementação do jeito que esta esteja correta:

Por exemplo se o usuário selecionar o menu **emissão**, o **operation_type** deve sempre ser **out**. 

**E isso nunca vai mudar,** se vc selecionar uma operação c/ operation_type = all e o campo for related. Não da mais pra saber se e uma operação de entrada ou saída.

2020-03-06 22:00 UTC, renatonlima approved these changes

2020-03-06 22:00 UTC, merged